/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.brc.policiaeladrao;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.security.SecureRandom;

/**
 *
 * @author User
 */
public class Formulario extends javax.swing.JFrame{

    /**
     * Creates new form Formulario
     */
    
    private Ladrao ladrao;
    private Policia policia;
    private boolean alg = true;
    
    public Formulario() {
        initComponents();
        imgLula.setVisible(false);
        imgTerry.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btResetar = new javax.swing.JButton();
        lbStatusAlgema = new javax.swing.JLabel();
        lbPoliciaTitulo = new javax.swing.JLabel();
        txtPoliciaRadio = new javax.swing.JTextField();
        btAlgemaTrue = new javax.swing.JButton();
        btAlgemaFalse = new javax.swing.JButton();
        lbPoliciaRadio = new javax.swing.JLabel();
        txtPoliciaNome = new javax.swing.JTextField();
        lbPoliciaNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbLadraoTitulo = new javax.swing.JLabel();
        lbLadraoNome = new javax.swing.JLabel();
        txtLadraoNome = new javax.swing.JTextField();
        lbLadraoVeiculo = new javax.swing.JLabel();
        txtLadraoVeiculo = new javax.swing.JTextField();
        lbLadraoComplexo = new javax.swing.JLabel();
        txtLadraoComplexo = new javax.swing.JTextField();
        btPoliciaCriar = new javax.swing.JButton();
        btLadraoCriar = new javax.swing.JButton();
        lbPoliciaBadge = new javax.swing.JLabel();
        lbLadraoIcon = new javax.swing.JLabel();
        lbPoliciaVida = new javax.swing.JLabel();
        mutPoliciaVida = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mutLadraoVida = new javax.swing.JLabel();
        btPoliciaAtirar = new javax.swing.JButton();
        imgPoliciaAtirar = new javax.swing.JLabel();
        imgLadraoAtirar = new javax.swing.JLabel();
        btLadraoAtirar = new javax.swing.JButton();
        btPoliciaArregar = new javax.swing.JButton();
        imgPoliciaArregar = new javax.swing.JLabel();
        imgPoliciaPrender = new javax.swing.JLabel();
        btPoliciaPrender = new javax.swing.JButton();
        imgPoliciaReforcos = new javax.swing.JLabel();
        btPoliciaReforcos = new javax.swing.JButton();
        imgLadraoFuga = new javax.swing.JLabel();
        btLadraoFuga = new javax.swing.JButton();
        imgLadraoArregar = new javax.swing.JLabel();
        btLadraoArregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btLadraoSequestrar = new javax.swing.JButton();
        imgTerry = new javax.swing.JLabel();
        mutUpdatePanel = new javax.swing.JLabel();
        txtPoliciaImgAlgemas = new javax.swing.JLabel();
        txtPoliciaImgRadio = new javax.swing.JLabel();
        txtPoliciaImgNome = new javax.swing.JLabel();
        txtLadraoImgNome = new javax.swing.JLabel();
        txtLadraoImgVeiculo = new javax.swing.JLabel();
        txtLadraoImgComplexo = new javax.swing.JLabel();
        imgLula = new javax.swing.JLabel();
        lbBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Polícia e Ladrão");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btResetar.setText("resetar");
        btResetar.setEnabled(false);
        btResetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetarActionPerformed(evt);
            }
        });
        getContentPane().add(btResetar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        lbStatusAlgema.setText("Com algemas");
        getContentPane().add(lbStatusAlgema, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 120, 20));

        lbPoliciaTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lbPoliciaTitulo.setForeground(new java.awt.Color(0, 0, 255));
        lbPoliciaTitulo.setText("Polícia");
        getContentPane().add(lbPoliciaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtPoliciaRadio.setForeground(new java.awt.Color(255, 0, 255));
        txtPoliciaRadio.setText("Hello Kitty Ultra");
        txtPoliciaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPoliciaRadioActionPerformed(evt);
            }
        });
        getContentPane().add(txtPoliciaRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 100, -1));

        btAlgemaTrue.setText("com");
        btAlgemaTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlgemaTrueActionPerformed(evt);
            }
        });
        getContentPane().add(btAlgemaTrue, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        btAlgemaFalse.setText("sem");
        btAlgemaFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlgemaFalseActionPerformed(evt);
            }
        });
        getContentPane().add(btAlgemaFalse, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        lbPoliciaRadio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPoliciaRadio.setText("Modelo rádio");
        getContentPane().add(lbPoliciaRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        txtPoliciaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPoliciaNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtPoliciaNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, -1));

        lbPoliciaNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPoliciaNome.setText("Nome");
        getContentPane().add(lbPoliciaNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Algemas?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        lbLadraoTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lbLadraoTitulo.setForeground(new java.awt.Color(255, 0, 0));
        lbLadraoTitulo.setText("Ladrão");
        getContentPane().add(lbLadraoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        lbLadraoNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbLadraoNome.setText("Nome");
        getContentPane().add(lbLadraoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txtLadraoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLadraoNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtLadraoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, -1));

        lbLadraoVeiculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbLadraoVeiculo.setText("Veiculo de Fuga");
        getContentPane().add(lbLadraoVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        txtLadraoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLadraoVeiculoActionPerformed(evt);
            }
        });
        getContentPane().add(txtLadraoVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 90, -1));

        lbLadraoComplexo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbLadraoComplexo.setText("Complexo");
        getContentPane().add(lbLadraoComplexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        txtLadraoComplexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLadraoComplexoActionPerformed(evt);
            }
        });
        getContentPane().add(txtLadraoComplexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 90, -1));

        btPoliciaCriar.setText("Criar");
        btPoliciaCriar.setToolTipText("");
        btPoliciaCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPoliciaCriarActionPerformed(evt);
            }
        });
        getContentPane().add(btPoliciaCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        btLadraoCriar.setText("Criar");
        btLadraoCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLadraoCriarActionPerformed(evt);
            }
        });
        getContentPane().add(btLadraoCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        lbPoliciaBadge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/brc/policiaeladrao/pixel-art-police-badge-police-department-vector-icon-8bit-game-white-background_360488-590-transformed.png"))); // NOI18N
        getContentPane().add(lbPoliciaBadge, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 80, 100));

        lbLadraoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/brc/policiaeladrao/1000_F_491447197_18uDwoiLpDtqEAWuX5Q2IKc3CceZQj95-transformed-tradnsformed (1).png"))); // NOI18N
        getContentPane().add(lbLadraoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 80, 100));

        lbPoliciaVida.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        lbPoliciaVida.setText("Vida: ");
        getContentPane().add(lbPoliciaVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        mutPoliciaVida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mutPoliciaVida.setText("0%");
        getContentPane().add(mutPoliciaVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 80, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel2.setText("Vida:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, -1, -1));

        mutLadraoVida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mutLadraoVida.setText("0%");
        getContentPane().add(mutLadraoVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, -1, -1));

        btPoliciaAtirar.setText("atirar");
        btPoliciaAtirar.setEnabled(false);
        btPoliciaAtirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPoliciaAtirarActionPerformed(evt);
            }
        });
        getContentPane().add(btPoliciaAtirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, -1));

        imgPoliciaAtirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/brc/policiaeladrao/espingarda.png"))); // NOI18N
        getContentPane().add(imgPoliciaAtirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 70, 20));

        imgLadraoAtirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/brc/policiaeladrao/pistola.png"))); // NOI18N
        getContentPane().add(imgLadraoAtirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 30, 30));

        btLadraoAtirar.setText("meter bala");
        btLadraoAtirar.setEnabled(false);
        btLadraoAtirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLadraoAtirarActionPerformed(evt);
            }
        });
        getContentPane().add(btLadraoAtirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, -1, -1));

        btPoliciaArregar.setText("desistir");
        btPoliciaArregar.setEnabled(false);
        btPoliciaArregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPoliciaArregarActionPerformed(evt);
            }
        });
        getContentPane().add(btPoliciaArregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, -1, -1));

        imgPoliciaArregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/brc/policiaeladrao/arregar.png"))); // NOI18N
        getContentPane().add(imgPoliciaArregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 30, 40));

        imgPoliciaPrender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/brc/policiaeladrao/algemasprender.png"))); // NOI18N
        getContentPane().add(imgPoliciaPrender, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 30, 30));

        btPoliciaPrender.setText("prender");
        btPoliciaPrender.setEnabled(false);
        btPoliciaPrender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPoliciaPrenderActionPerformed(evt);
            }
        });
        getContentPane().add(btPoliciaPrender, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        imgPoliciaReforcos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/brc/policiaeladrao/reforcos.png"))); // NOI18N
        getContentPane().add(imgPoliciaReforcos, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 30, 40));

        btPoliciaReforcos.setText("chamar reforcos");
        btPoliciaReforcos.setEnabled(false);
        btPoliciaReforcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPoliciaReforcosActionPerformed(evt);
            }
        });
        getContentPane().add(btPoliciaReforcos, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, -1, -1));

        imgLadraoFuga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/brc/policiaeladrao/ladraofuga.png"))); // NOI18N
        getContentPane().add(imgLadraoFuga, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 30, 30));

        btLadraoFuga.setText("dar a fuga");
        btLadraoFuga.setEnabled(false);
        btLadraoFuga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLadraoFugaActionPerformed(evt);
            }
        });
        getContentPane().add(btLadraoFuga, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, -1, -1));

        imgLadraoArregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/brc/policiaeladrao/arregar.png"))); // NOI18N
        getContentPane().add(imgLadraoArregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, -1, 30));

        btLadraoArregar.setText("arregar");
        btLadraoArregar.setEnabled(false);
        btLadraoArregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLadraoArregarActionPerformed(evt);
            }
        });
        getContentPane().add(btLadraoArregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/brc/policiaeladrao/sequestrar.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, -1, 40));

        btLadraoSequestrar.setText("sequestrar puliça");
        btLadraoSequestrar.setEnabled(false);
        btLadraoSequestrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLadraoSequestrarActionPerformed(evt);
            }
        });
        getContentPane().add(btLadraoSequestrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, -1, -1));

        imgTerry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/brc/policiaeladrao/pfvfunciona.png"))); // NOI18N
        getContentPane().add(imgTerry, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 60, 70));

        mutUpdatePanel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        mutUpdatePanel.setForeground(new java.awt.Color(255, 255, 255));
        mutUpdatePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(mutUpdatePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 370, 60));

        txtPoliciaImgAlgemas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtPoliciaImgAlgemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 120, 20));

        txtPoliciaImgRadio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPoliciaImgRadio.setForeground(new java.awt.Color(255, 51, 255));
        getContentPane().add(txtPoliciaImgRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 130, 20));

        txtPoliciaImgNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtPoliciaImgNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 120, 20));

        txtLadraoImgNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLadraoImgNome.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtLadraoImgNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 140, 20));

        txtLadraoImgVeiculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLadraoImgVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtLadraoImgVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 140, 20));

        txtLadraoImgComplexo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLadraoImgComplexo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtLadraoImgComplexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 140, 20));

        imgLula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/brc/policiaeladrao/lulaicon.png"))); // NOI18N
        getContentPane().add(imgLula, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, -1));

        lbBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/brc/policiaeladrao/backgroundx.png"))); // NOI18N
        getContentPane().add(lbBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAlgemaTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlgemaTrueActionPerformed
        btAlgemaTrue.setForeground(Color.blue);
        btAlgemaFalse.setForeground(Color.BLACK);
        this.alg = true;
        lbStatusAlgema.setText("Com algemas");
    }//GEN-LAST:event_btAlgemaTrueActionPerformed

    private void txtPoliciaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPoliciaNomeActionPerformed
        
    }//GEN-LAST:event_txtPoliciaNomeActionPerformed

    private void txtLadraoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLadraoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLadraoNomeActionPerformed

    private void txtLadraoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLadraoVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLadraoVeiculoActionPerformed

    private void txtLadraoComplexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLadraoComplexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLadraoComplexoActionPerformed

    private void btPoliciaCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPoliciaCriarActionPerformed
        if (txtPoliciaNome.getText().equals("") || txtPoliciaRadio.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Crie o policial rapá");
            return;
        }
        policia = new Policia(
                txtPoliciaNome.getText(), 
                alg, 
                txtPoliciaRadio.getText());
        btPoliciaAtirar.setEnabled(true);
        btPoliciaPrender.setEnabled(true);
        btPoliciaReforcos.setEnabled(true);
        btPoliciaArregar.setEnabled(true);
        mutPoliciaVida.setText(String.valueOf(policia.vidaAtual) + "%");
        btAlgemaFalse.setEnabled(false);
        btAlgemaTrue.setEnabled(false);
        btPoliciaCriar.setEnabled(false);
        txtPoliciaNome.setText("");
        txtPoliciaRadio.setText("");
        txtPoliciaImgNome.setText("nome: "+ policia.nome);
        txtPoliciaImgRadio.setText("radin: " + policia.radio);
        imgTerry.setVisible(true);
        if (alg) {
            txtPoliciaImgAlgemas.setText("a l g e m a d o");
        }
        else {
            txtPoliciaImgAlgemas.setText("Sem as algemas");
        }
    }//GEN-LAST:event_btPoliciaCriarActionPerformed

    private void txtPoliciaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPoliciaRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPoliciaRadioActionPerformed

    private void btLadraoAtirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLadraoAtirarActionPerformed
        SecureRandom random = new SecureRandom();
        if (policia == null) {
            return;
        }
        mutUpdatePanel.setText(ladrao.atirar(policia));
        mutPoliciaVida.setText(String.valueOf(policia.vidaAtual));
        if (policia.vidaAtual == 0) {
            JOptionPane.showMessageDialog(null,String.format("%s foi de base.", policia.nome));
            btPoliciaAtirar.setEnabled(false);
            btPoliciaArregar.setEnabled(false);
            btPoliciaPrender.setEnabled(false);
            btPoliciaReforcos.setEnabled(false);
            btLadraoAtirar.setEnabled(false);
            btLadraoArregar.setEnabled(false);
            btLadraoSequestrar.setEnabled(false);
            btResetar.setEnabled(true);
        }
        Color[] cores = {Color.RED, Color.DARK_GRAY, Color.cyan};
        mutPoliciaVida.setForeground(cores[random.nextInt(cores.length - 1)]);
    }//GEN-LAST:event_btLadraoAtirarActionPerformed

    private void btPoliciaReforcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPoliciaReforcosActionPerformed
        if (ladrao == null) {
            JOptionPane.showMessageDialog(null, "Chamar reforços pra quem? Não tem ladrão");
            return;
        }
        mutUpdatePanel.setText(policia.chamarReforcos());
        btPoliciaArregar.setEnabled(false);
        btPoliciaReforcos.setEnabled(false);
        btLadraoFuga.setEnabled(false);
        btLadraoSequestrar.setEnabled(false);
        btLadraoAtirar.setEnabled(true);
        btPoliciaAtirar.setEnabled(true);
    }//GEN-LAST:event_btPoliciaReforcosActionPerformed

    private void btLadraoSequestrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLadraoSequestrarActionPerformed
        if (policia == null) {
            return;
        }
        mutUpdatePanel.setText(ladrao.sequestrar(policia));
        btPoliciaArregar.setEnabled(false);
        btPoliciaAtirar.setEnabled(false);
        btPoliciaPrender.setEnabled(false);
        btPoliciaReforcos.setEnabled(false);
        btLadraoArregar.setEnabled(false);
        btLadraoFuga.setEnabled(false);
        btLadraoSequestrar.setEnabled(false);
    }//GEN-LAST:event_btLadraoSequestrarActionPerformed

    private void btLadraoCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLadraoCriarActionPerformed
        if (txtLadraoNome.getText().equals("") || 
                txtLadraoVeiculo.getText().equals("")||
                txtLadraoComplexo.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Crie o ladrão :p");
            return;
        }
        ladrao = new Ladrao(
                txtLadraoNome.getText(), 
                txtLadraoVeiculo.getText(), 
                txtLadraoComplexo.getText());
        
        btLadraoAtirar.setEnabled(true);
        btLadraoFuga.setEnabled(true);
        btLadraoArregar.setEnabled(true);
        btLadraoSequestrar.setEnabled(true);
        mutLadraoVida.setText(String.valueOf(ladrao.vidaAtual) + "%");
        btLadraoCriar.setEnabled(false);
        imgLula.setVisible(true);
        txtLadraoImgNome.setText("nome: "+ ladrao.nome);
        txtLadraoImgVeiculo.setText("veiculo: " + ladrao.veiculoDeFuga);
        txtLadraoImgComplexo.setText("complexo: " + ladrao.complexo);
        txtLadraoNome.setText("");
        txtLadraoVeiculo.setText("");
        txtLadraoComplexo.setText("");
    }//GEN-LAST:event_btLadraoCriarActionPerformed

    private void btPoliciaAtirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPoliciaAtirarActionPerformed
        if (ladrao == null) {
            JOptionPane.showMessageDialog(null,"Não tem ninguém pra você atirar..");
            return;
        }
        SecureRandom random = new SecureRandom();
        mutUpdatePanel.setText(policia.atirar(ladrao));
        mutLadraoVida.setText(String.valueOf(ladrao.vidaAtual));
        if (ladrao.vidaAtual == 0) {
            JOptionPane.showMessageDialog(null,String.format("%s FOI DE BASE. RIP", ladrao.nome));
            btLadraoArregar.setEnabled(false);
            btLadraoAtirar.setEnabled(false);
            btLadraoFuga.setEnabled(false);
            btLadraoSequestrar.setEnabled(false);
            btPoliciaArregar.setEnabled(false);
            btPoliciaAtirar.setEnabled(false);
            btPoliciaPrender.setEnabled(false);
            btPoliciaReforcos.setEnabled(false);
            btResetar.setEnabled(true);
        }
        Color[] cores = {Color.RED, Color.DARK_GRAY, Color.cyan};
        mutLadraoVida.setForeground(cores[random.nextInt(cores.length - 1)]);
    }//GEN-LAST:event_btPoliciaAtirarActionPerformed

    private void btPoliciaPrenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPoliciaPrenderActionPerformed
        if (ladrao == null) {
            JOptionPane.showMessageDialog(null,"Vai prender quem, doidão?");
            return;
        }
        mutUpdatePanel.setText(policia.prender(ladrao));
        if (!alg) {
            return;
        }
        btLadraoAtirar.setEnabled(false);
        btLadraoFuga.setEnabled(false);
        btLadraoSequestrar.setEnabled(false);
        btLadraoArregar.setEnabled(false);
        btPoliciaArregar.setEnabled(false);
        btPoliciaPrender.setEnabled(false);
        btPoliciaReforcos.setEnabled(false);
        btResetar.setEnabled(true);
    }//GEN-LAST:event_btPoliciaPrenderActionPerformed

    private void btPoliciaArregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPoliciaArregarActionPerformed
        mutUpdatePanel.setText(policia.arregar());
        btPoliciaAtirar.setEnabled(false);
        btPoliciaArregar.setEnabled(false);
        btPoliciaPrender.setEnabled(false);
        btPoliciaReforcos.setEnabled(false);
        btLadraoAtirar.setEnabled(false);
        btLadraoSequestrar.setEnabled(false);
        btLadraoArregar.setEnabled(false);
        btResetar.setEnabled(true);
        btLadraoCriar.setEnabled(false);
    }//GEN-LAST:event_btPoliciaArregarActionPerformed

    private void btAlgemaFalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlgemaFalseActionPerformed
        btAlgemaFalse.setForeground(Color.blue);
        btAlgemaTrue.setForeground(Color.BLACK);
        alg = false;
        lbStatusAlgema.setText("Sem algemas");
    }//GEN-LAST:event_btAlgemaFalseActionPerformed

    private void btLadraoFugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLadraoFugaActionPerformed
        if (policia == null) { return; }
        mutUpdatePanel.setText(ladrao.fugir());
        btPoliciaAtirar.setEnabled(false);
        btPoliciaPrender.setEnabled(false);
        btLadraoArregar.setEnabled(false);
        btLadraoSequestrar.setEnabled(false);
        btLadraoFuga.setEnabled(false);
        btLadraoAtirar.setEnabled(false);
    }//GEN-LAST:event_btLadraoFugaActionPerformed

    private void btLadraoArregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLadraoArregarActionPerformed
        mutUpdatePanel.setText(ladrao.arregar());
        btPoliciaAtirar.setEnabled(false);
        btPoliciaArregar.setEnabled(false);
        btPoliciaPrender.setEnabled(false);
        btPoliciaReforcos.setEnabled(false);
        btLadraoAtirar.setEnabled(false);
        btLadraoFuga.setEnabled(false);
        btLadraoSequestrar.setEnabled(false);
        btLadraoArregar.setEnabled(false);
        btResetar.setEnabled(true);
        btPoliciaCriar.setEnabled(false);
    }//GEN-LAST:event_btLadraoArregarActionPerformed

    private void btResetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetarActionPerformed
        ladrao = null;
        policia = null;
        btLadraoArregar.setEnabled(false);
        btLadraoAtirar.setEnabled(false);
        btLadraoCriar.setEnabled(true);
        btLadraoFuga.setEnabled(false);
        btLadraoSequestrar.setEnabled(false);
        btPoliciaArregar.setEnabled(false);
        btPoliciaAtirar.setEnabled(false);
        btPoliciaPrender.setEnabled(false);
        btPoliciaReforcos.setEnabled(false);
        btPoliciaCriar.setEnabled(true);
        btAlgemaTrue.setEnabled(true);
        btAlgemaFalse.setEnabled(true);
        mutLadraoVida.setText("0%");
        mutPoliciaVida.setText("0%");
        txtLadraoImgNome.setText("");
        txtLadraoImgComplexo.setText("");
        txtLadraoImgVeiculo.setText("");
        txtPoliciaImgNome.setText("");
        txtPoliciaImgAlgemas.setText("");
        txtPoliciaImgRadio.setText("");
        imgLula.setVisible(false);
        btResetar.setEnabled(false);
        imgTerry.setVisible(false);
    }//GEN-LAST:event_btResetarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlgemaFalse;
    private javax.swing.JButton btAlgemaTrue;
    private javax.swing.JButton btLadraoArregar;
    private javax.swing.JButton btLadraoAtirar;
    private javax.swing.JButton btLadraoCriar;
    private javax.swing.JButton btLadraoFuga;
    private javax.swing.JButton btLadraoSequestrar;
    private javax.swing.JButton btPoliciaArregar;
    private javax.swing.JButton btPoliciaAtirar;
    private javax.swing.JButton btPoliciaCriar;
    private javax.swing.JButton btPoliciaPrender;
    private javax.swing.JButton btPoliciaReforcos;
    private javax.swing.JButton btResetar;
    private javax.swing.JLabel imgLadraoArregar;
    private javax.swing.JLabel imgLadraoAtirar;
    private javax.swing.JLabel imgLadraoFuga;
    private javax.swing.JLabel imgLula;
    private javax.swing.JLabel imgPoliciaArregar;
    private javax.swing.JLabel imgPoliciaAtirar;
    private javax.swing.JLabel imgPoliciaPrender;
    private javax.swing.JLabel imgPoliciaReforcos;
    private javax.swing.JLabel imgTerry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbBG;
    private javax.swing.JLabel lbLadraoComplexo;
    private javax.swing.JLabel lbLadraoIcon;
    private javax.swing.JLabel lbLadraoNome;
    private javax.swing.JLabel lbLadraoTitulo;
    private javax.swing.JLabel lbLadraoVeiculo;
    private javax.swing.JLabel lbPoliciaBadge;
    private javax.swing.JLabel lbPoliciaNome;
    private javax.swing.JLabel lbPoliciaRadio;
    private javax.swing.JLabel lbPoliciaTitulo;
    private javax.swing.JLabel lbPoliciaVida;
    private javax.swing.JLabel lbStatusAlgema;
    private javax.swing.JLabel mutLadraoVida;
    private javax.swing.JLabel mutPoliciaVida;
    private javax.swing.JLabel mutUpdatePanel;
    private javax.swing.JTextField txtLadraoComplexo;
    private javax.swing.JLabel txtLadraoImgComplexo;
    private javax.swing.JLabel txtLadraoImgNome;
    private javax.swing.JLabel txtLadraoImgVeiculo;
    private javax.swing.JTextField txtLadraoNome;
    private javax.swing.JTextField txtLadraoVeiculo;
    private javax.swing.JLabel txtPoliciaImgAlgemas;
    private javax.swing.JLabel txtPoliciaImgNome;
    private javax.swing.JLabel txtPoliciaImgRadio;
    private javax.swing.JTextField txtPoliciaNome;
    private javax.swing.JTextField txtPoliciaRadio;
    // End of variables declaration//GEN-END:variables
}
